client_config_backend: settings
client_config:
  client_id: 522995636928-4pn8ujr0cufvmtdt1a9nt443rhpd8rcr.apps.googleusercontent.com
  client_secret: 9n5JYfPeRgv9I2PKMIAr6WFE

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
